import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  webTasarimi: [{type: 'autogenerated', dirName: 'web-tasarimi'}],
  algoritmaVeProgramlama: [{type: 'autogenerated', dirName: 'algoritma-ve-programlama'}],
  temelBilgiTeknolojileri: [{type: 'autogenerated', dirName: 'temel-bilgi-teknolojileri'}],
  webOkuryazarligi: [{type: 'autogenerated', dirName: 'web-okuryazarligi'}],
  matematik: [{type: 'autogenerated', dirName: 'matematik'}],
  ataturkIlkeleriVeInkilapTarihi: [{type: 'autogenerated', dirName: 'ataturk-ilkeleri-ve-inkilap-tarihi'}],
  isSagligiVeGuvenligi: [{type: 'autogenerated', dirName: 'is-sagligi-ve-guvenligi'}],
  kariyerPlanlama: [{type: 'autogenerated', dirName: 'kariyer-planlama'}],
  turkDili: [{type: 'autogenerated', dirName: 'turk-dili'}],
  yabanciDil: [{type: 'autogenerated', dirName: 'yabanci-dil'}],

  // But you can create a sidebar manually

  /*tutorialSidebar: [
    'intro',
    'giris',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],*/
};

export default sidebars;
